export const GET_PLAYERHISTORIES = "GET_PLAYERHISTORIES"
export const POST_PLAYERHISTORIES = "POST_PLAYERHISTORIES"
export const UPDATE_PLAYERHISTORIES = "UPDATE_PLAYERHISTORIES"
export const DELETE_PLAYERHISTORIES = "DELETE_PLAYERHISTORIES"