export const GET_ALLCONTENTS = "GET_ALLCONTENTS"
export const POST_ALLCONTENTS = "POST_ALLCONTENTS"
export const UPDATE_ALLCONTENTS = "UPDATE_ALLCONTENTS"
export const DELETE_ALLCONTENTS = "DELETE_ALLCONTENTS"